name: shopping_list_demo
description: Demo project of testing and persistance in Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.2

  # Mocktail dep
  mocktail: ^1.0.4

  # Freezed deps
  freezed: ^2.5.7

dev_dependencies:
  flutter_lints: ^2.0.0

  # Common dep
  build_runner: ^2.4.13

  # Freezed deps
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.0

  # Common testing deps
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Goldens testing dep
  golden_toolkit: 0.15.0

flutter:
  uses-material-design: true
