// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/model/shopping_item_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4783952937822256735),
      name: 'ShoppingItemEntity',
      lastPropertyId: const obx_int.IdUid(4, 4932390236364893457),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6765604912425758891),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8440332576779600804),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 7892415693276126267)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4001968785259530400),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4932390236364893457),
            name: 'isBought',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 4783952937822256735),
      lastIndexId: const obx_int.IdUid(1, 7892415693276126267),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ShoppingItemEntity: obx_int.EntityDefinition<ShoppingItemEntity>(
        model: _entities[0],
        toOneRelations: (ShoppingItemEntity object) => [],
        toManyRelations: (ShoppingItemEntity object) => {},
        getId: (ShoppingItemEntity object) => object.id,
        setId: (ShoppingItemEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ShoppingItemEntity object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addBool(3, object.isBought);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final isBoughtParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final object = ShoppingItemEntity(
              id: idParam,
              uid: uidParam,
              name: nameParam,
              isBought: isBoughtParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ShoppingItemEntity] entity fields to define ObjectBox queries.
class ShoppingItemEntity_ {
  /// See [ShoppingItemEntity.id].
  static final id =
      obx.QueryIntegerProperty<ShoppingItemEntity>(_entities[0].properties[0]);

  /// See [ShoppingItemEntity.uid].
  static final uid =
      obx.QueryStringProperty<ShoppingItemEntity>(_entities[0].properties[1]);

  /// See [ShoppingItemEntity.name].
  static final name =
      obx.QueryStringProperty<ShoppingItemEntity>(_entities[0].properties[2]);

  /// See [ShoppingItemEntity.isBought].
  static final isBought =
      obx.QueryBooleanProperty<ShoppingItemEntity>(_entities[0].properties[3]);
}
